### PR TITLE
fix: Don't hide cursor with context

### LINKED ISSUE #28: Cursor is hidden behing context window
I use `zt` to scroll the current line to the top. A normal use case is to check a code block inside a long function.

However the top line will be overlapped by context line and this is annoying. Suggest remap `zt` to move the scroll the current line to the 2nd top line.

### PR DESCRIPTION
**Pull request by lewis6991**
Fixes romgrk/nvim-treesitter-context#28

### CODE REVIEW

**Comment by Jasha10** [comment]
Thanks @lewis6991, I agree that this approach is more elegant than that in my PR #8.

I've tested out the implementation; it is working well when I set `max_lines` to a positive integer.
When I set `max_lines` to zero, it seems that only one line of context is displayed (even when the cursor is far away from the top of the window).

**Comment by Jasha10** [comment]
I guess I was just a little bit too slow in my comment xD

**Comment by lewis6991** [comment]
Ah sorry, I was too quick to merge. I'll look into the issue.

**Comment by Jasha10** [comment]
I think I have a fix for it.
Edit: I've submitted PR #11 with a fix.

**Pull request merged**
