### PR TITLE
feat: show *section context in tex files

### PR DESCRIPTION
**Pull request by brokenbyte**

### CODE REVIEW

**Comment by clason** [comment]
I'd add at least `chapter` as well. You can see the full list of sectioning commands used by the parser in
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/latex/folds.scm

The other environments are probably less useful as-is, although I personally would like to see at least some environments in context. I don't know if it's possible to expose, say
```latex
\begin{theorem}
 ...
\end{theorem}
```
(which is a `generic_environment`) as `Theorem` (and similarly for others).

**Comment by brokenbyte** [comment]
Good point about chapter, I don't use them so I didn't think about it. AFA theorems and other environments, I don't really know how treesitter handles those, and I have finals coming up in about 2 weeks, so definitely won't have much time to dig into it until after that. If you have some resources that might help I can look into it when I have a chance though!

**Comment by clason** [comment]
Well, the [latex grammar](https://github.com/latex-lsp/tree-sitter-latex/blob/master/grammar.js), of course ;) You can also check the highlight queries in nvim-treesitter; they show how these are used in queries.

https://github.com/nvim-treesitter/playground is also your friend to see these in action.

**Comment by brokenbyte** [comment]
Ah fair enough, makes sense. I noticed there's a specific node for [minted](https://github.com/latex-lsp/tree-sitter-latex/blob/master/grammar.js#L82), so I imagine we'd need something similar for a theorem environment right?

Seems like adding that would require some changes to nvim-treesitter proper before we could show them as context here?

**Comment by clason** [comment]
No, theorem environments are `generic_environments`, they are captured like here:
https://github.com/nvim-treesitter/nvim-treesitter/blob/bd2f5d770d0a98b1d89bb95dab7ca396b01ce1fe/queries/latex/highlights.scm#L33-L35

No changes in nvim-treesitter are needed here, but probably some in this plugin (which @lewis6991 might not want to make, and that's fine).

**Comment by lewis6991** [comment]
@clason what do you think of this PR? I don't really have an opinion but looks reasonable.

**Comment by clason** [comment]
The selection of sectioning is a bit opinionated (why no "part" or "(sub)paragraph"?), but it's better than nothing :)

Adding environments to the mix is surely more complicated and likely outside the scope of this PR.

**Comment by lewis6991** [comment]
Ok we can just go with it then.

**Pull request merged**
