### PR TITLE
Feature advance mode, relative number, auto max lines and fix some issues

### LINKED ISSUE #91: parent item is not shown in context when it's on the first line
Thanks for the awesome plugin! 

I found some strange behavior and I'm not sure where this is coming from. 

A function item that is the first line will not be shown in the context. 

I tested this with rust and python examples. 

So in a file like this: 
```python
def test():
    print("A")
    # [...] more content so the function definition is outside the screen
    print("A) # cursor here 
```
The function will not be shown in the context. 

Slightly changed like this: 

```python
# empty line here
def test():
    print("A")
    # [...] more content so the function definition is outside the screen
    print("A) # cursor here 
```

I will see the function in the context. 

I'm happy to provide more input when needed.

### PR DESCRIPTION
**Pull request by binhtddev**
Now, I am very busy to write document about advance mode, just have the implementation example about java in advances folder. This may fix some issue like romgrk#72, romgrk#53,...
In addition, I also fix romgrk#91 and romgrk#80.

Before:

before

After:

after

### CODE REVIEW

**Comment by binhtddev** [comment]
I also add new feature to auto detect max_lines base on cursor.
This is demo with scrolloff = 3, auto_max_lines = true, auto_max_lines_padding = 1:

auto_max_lines

**Comment by binhtddev** [comment]
I notice that the topline is wrong with folding exists between topline and cursor line, so I merge with my another PR #2 to reuse the algorithm calculating relative line.
All together with scrolloff = 3, advances.enable = true, fake_relative_number = true, auto_max_lines = true, auto_max_lines_padding = 1
all_together

**Comment by lewis6991** [comment]
Sorry I didn't reply earlier. I didn't have notifications turned on for this fork.

This PR is quite big, would it be possible to introduce changes in smaller PR's to make this easier to review?

I'm also not sure what advance mode even does.

**Comment by binhtddev** [comment]
Sorry I'm busy right now. Only a short description is that it makes use of treesitter to solve some complex nodes like annotation, else,... in java (I've only written for java).

I'm closing for now to create a new cleaner PR, but I believe this will be the future of this plugin.

And I also solved some other problems like relative line number, show hidden context work with folding.

Because I disable all my features by default, if you want to test, just switch the config in my README.md.

**Pull request closed without merging**
