### PR TITLE
Feat: Add cursor padding and refactor algorithm get parents

### PR DESCRIPTION
**Pull request by binhtddev**
This is the rebase of #15 with new feature config "cursor_padding" is default to 0. It use with user setting "scrolloff" for better experiment (also part of #3).
This also refactors the algorithm to solve romgrk#80

### CODE REVIEW

**Comment by lewis6991** [comment]
There are too many unrelated changes in this PR which makes it very difficult to review. Commit 1 and 3 look ok, but it is not clear at all what commit 2 is for.

**Comment by binhtddev** [comment]
> There are too many unrelated changes in this PR which makes it very difficult to review. Commit 1 and 3 look ok, but it is not clear at all what commit 2 is for.

Commit 2 is a refactor of the algorithm to make context show near cursor instead of top context when using max line.

**Comment by lewis6991** [comment]
Sorry I still don't understand

**Comment by lewis6991** [comment]
The main repo is now being maintained, so closing open PR's here.

**Pull request closed without merging**
